version: '3'

services:
  kachaka_project:
    image: weblab/v1-kachaka-jazzy:latest
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=1
    networks:
      - ros2
    ipc: host
    privileged: true
    volumes: 
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/app/
    command: /app/docker/scripts/initialize-docker-container.sh
    stdin_open: true
    tty: true
    extra_hosts:
      - "display:host-gateway"
networks:
  ros2:
    driver: bridge